package com.cognizant.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.cognizant.Helpers;

@DynamoDBTable(tableName="TikTakTable")
public class SingleTableModel {
	private String pk;
	private String sk;
	
	private final String pkPrefix;
	private int pkPrefixLen;

	private final String skPrefix;
	private int skPrefixLen;
	
	public SingleTableModel(String pkPrefix,
			String pk,String skPrefix, String sk) throws IllegalArgumentException {
		if (pkPrefix == null) {
			throw new IllegalArgumentException("pkPrefix is null");
		}
		if (skPrefix == null) {
			throw new IllegalArgumentException("skPrefix is null");
		}

		this.pkPrefix = pkPrefix;
		this.skPrefix = skPrefix;

		this.pkPrefixLen = pkPrefix.length();
		this.skPrefixLen = skPrefix.length();

		if (pkPrefixLen <= 0) {
			throw new IllegalArgumentException("pkPrefix length is not > 0");
		}
		if (skPrefixLen <= 0) {
			throw new IllegalArgumentException("skPrefix length is not > 0");
		}

		this.pk = pk;
		this.sk = sk;
	}

	@DynamoDBHashKey(attributeName = "PK")
	public String getPkQuery() throws IllegalStateException {
		if (pk == null) {
			throw new IllegalStateException("PK is null");
		}
        return pkPrefix + "#" + pk;
	}
	public void setPkQuery(String pkQuery) {
		pk = pkQuery.substring(pkPrefixLen + 1);
	}

	@DynamoDBAutoGeneratedKey
	public String getPk() {
		return pk;
	}
	public void setPk(String pk) {
		this.pk = pk;
	}

	@DynamoDBRangeKey(attributeName = "SK")
	public String getSkQuery() throws IllegalStateException {
		if (sk == null) {
			throw new IllegalStateException("SK is null");
		}
        return skPrefix + "#" + sk;
	}
	public void setSkQuery(String skQuery) {
		sk = skQuery.substring(skPrefixLen + 1);
	}

	@DynamoDBAutoGeneratedKey
	public String getSk() {
		return sk;
	}
	public void setSk(String sk) {
		this.pk = sk;
	}
} 
