AWSTemplateFormatVersion: 2010-09-09
Description: AWS CloudFormation Template for TikTak node CodeDeploy

Parameters:
  CodeDeployRoleArn:
    Description: Code Deploy Role Arn
    Type: String

  Repository:
    Description: Github Repository for Code Deploy
    Type: String

      # CommitId:
      #   Description: Github CommitId for Code Deploy
      #   Type: String

Resources:
  # CodeDeployConfig:
  #   Type: AWS::CodeDeploy::DeploymentConfig
  #   Properties:
  #     DeploymentConfigName: TikTakCodeDeployConfig
  #     MinimumHealthyHosts:
  #       Type: "HOST_COUNT"
  #       Value: 1

  CodeDeployApplication:
    Type: AWS::CodeDeploy::Application
    # DependsOn: CodeDeployConfig
    Properties:
      ApplicationName: TikTakApplication
      ComputePlatform: Server

  DeploymentGroup:
    Type: AWS::CodeDeploy::DeploymentGroup
    DependsOn: CodeDeployApplication
    Properties:
      ApplicationName: !Ref CodeDeployApplication
      # DeploymentGroupName: !Sub "${CodeDeployApplication}_TiktakDeploymentGroup"
      # Deployment:
      #   Description: "Code Deployment ${CommitId}"
      #   IgnoreApplicationStopFailures: true
      #   Revision:
      #     RevisionType: GitHub
      #     GitHubLocation:
      #       CommitId:
      #         Ref: CommitId
      #       Repository:
      #         Ref: Repository
      DeploymentConfigName: CodeDeployDefault.AllAtOnce
      ServiceRoleArn: !Ref CodeDeployRoleArn
      Ec2TagFilters:
        -
          Key: Name
          Value: TikTakEC2
          Type: KEY_AND_VALUE

Outputs:
  CodeDeployApplication:
    Description: TikTak Code Deploy Application
    Value: !Ref CodeDeployApplication

  CodeDeployGroupName:
    Description: TikTak Code Deploy Group Name
    Value: !Ref DeploymentGroup
