AWSTemplateFormatVersion: 2010-09-09
Description: AWS CloudFormation Template for TikTak Keypairs and Users

Parameters:
  DynamoDBPolicyArn:
    Type: String
    Description: TikTak DynamoDB Policy Arn

Resources:
  TikTakBackendRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
              - ec2.amazonaws.com
            Action:
              - "sts:AssumeRole"
                # - "autoscaling:Describe*"
                # - "cloudformation:Describe*"
                # - "cloudformation:GetTemplate",

      ManagedPolicyArns:
        - !Ref DynamoDBPolicyArn
        - 'arn:aws:iam::aws:policy/service-role/AmazonEC2RoleforAWSCodeDeploy'
        - 'arn:aws:iam::aws:policy/service-role/AutoScalingNotificationAccessRole'

      Tags:
        -
          Key: Name
          Value: TikTakBackendRole

  CodeDeployRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
              - codedeploy.amazonaws.com
            Action:
              - 'sts:AssumeRole'

      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AWSCodeDeployRole'
          # - 'arn:aws:iam::aws:policy/service-role/AmazonEC2RoleforAWSCodeDeploy'
          # - 'arn:aws:iam::aws:policy/service-role/AutoScalingNotificationAccessRole'

      Tags:
        -
          Key: Name
          Value: CodeDeployRole

Outputs:
  BackendRoleName:
    Description: TikTak Backend Role Name
    Value: !Ref TikTakBackendRole
  BackendRoleArn:
    Description: TikTak Backend Role Arn
    Value: !GetAtt TikTakBackendRole.Arn

  CodeDeployRoleName:
    Description: Code Deploy Role Name
    Value: !Ref CodeDeployRole
  CodeDeployRoleArn:
    Description: Code Deploy Role Arn
    Value: !GetAtt CodeDeployRole.Arn
