AWSTemplateFormatVersion: 2010-09-09

Parameters:
  WebsiteBucketName:
    Description: Name of S3 website bucket
    Type: String
  BuildBucketName:
    Description: Name of S3 build bucket
    Type: String

Resources:
  S3Website:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref WebsiteBucketName
      AccessControl: PublicRead
        # VersioningConfiguration:
        #   Status: Suspended
      WebsiteConfiguration:
        IndexDocument: index.html
          # ErrorDocument: 404.html
    DeletionPolicy: Delete

  S3WebsiteBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref S3Website
      PolicyDocument:
        Statement:
          - Action:
              - "s3:GetObject"
            Effect: Allow
            Resource:
              - !Join [ '', [ 'arn:aws:s3:::', !Ref S3Website, '/*' ] ]
            Principal: "*"

  S3Build:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BuildBucketName
      AccessControl: Private
      VersioningConfiguration:
        Status: Enabled
          # DeletionPolicy: Delete

Outputs:
  S3WebsiteDomain:
    Description: S3 Website Domain name
    Value: !GetAtt S3Website.DomainName

  S3WebsiteURL:
    Description: S3 Website URL
    Value: !GetAtt S3Website.WebsiteURL

  S3Website:
    Description: S3 Website Bucket
    Value: !Ref S3Website

  S3BuildDomain:
    Description: S3 Build Domain name
    Value: !GetAtt S3Build.DomainName

  S3Build:
    Description: S3 Build Bucket
    Value: !Ref S3Build
