AWSTemplateFormatVersion: 2010-09-09
Description: AWS CloudFormation Template for TikTak Project

Parameters:
  ConfigBucketUrl:
    Description: URL of S3 config bucket
    Type: String
  WebsiteBucketName:
    Description: Name of S3 website bucket
    Type: String
  BuildBucketName:
    Description: Name of S3 build bucket
    Type: String

  KeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instance
    Type: AWS::EC2::KeyPair::KeyName
    ConstraintDescription: must be the name of an existing EC2 KeyPair.
    Default: tiktak-ec2-keypair

  FrontendRepository:
    Description: Github Repository for Code Deploy
    Type: String
  BackendRepository:
    Description: Github Repository for Code Deploy
    Type: String
      # CommitId:
      #   Description: Github CommitId for Code Deploy
      #   Type: String

Resources:
  DynamoDBStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Join
        - ''
        - - "https://"
          - !Ref ConfigBucketUrl
          - /
          - dynamodb.yaml

  IAMStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Join
        - ''
        - - "https://"
          - !Ref ConfigBucketUrl
          - /
          - iam.yaml
      Parameters:
        DynamoDBPolicyArn: !GetAtt DynamoDBStack.Outputs.DynamoDBPolicyArn

  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Join
        - ''
        - - "https://"
          - !Ref ConfigBucketUrl
          - /
          - vpc.yaml
      Parameters:
        EnvironmentName: "TikTak"

  EC2Stack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Join
        - ''
        - - "https://"
          - !Ref ConfigBucketUrl
          - /
          - ec2.yaml

      Parameters:
        KeyName: !Ref KeyName
        SubnetId: !GetAtt VPCStack.Outputs.PublicSubnet1
        VPC: !GetAtt VPCStack.Outputs.VPC
        BackendRoleName: !GetAtt IAMStack.Outputs.BackendRoleName
        CodeDeployRoleName: !GetAtt IAMStack.Outputs.CodeDeployRoleName
        BackendPort: 8080

  CodeBuildStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Join
        - ''
        - - "https://"
          - !Ref ConfigBucketUrl
          - /
          - codebuild.yaml

      Parameters:
        ServiceRoleArn: !GetAtt IAMStack.Outputs.CodeBuildRoleArn

  S3Stack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Join
        - ''
        - - "https://"
          - !Ref ConfigBucketUrl
          - /
          - s3.yaml
      Parameters:
        WebsiteBucketName: !Ref WebsiteBucketName
        BuildBucketName: !Ref BuildBucketName

  CodeDeployStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: EC2Stack
    Properties:
      TemplateURL: !Join
        - ''
        - - "https://"
          - !Ref ConfigBucketUrl
          - /
          - codedeploy.yaml
      Parameters:
        CodeDeployRoleArn: !GetAtt IAMStack.Outputs.CodeDeployRoleArn
        Repository: !Ref BackendRepository
          # CommitId: !Ref CommitId


  CodePipelineStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Join
        - ''
        - - "https://"
          - !Ref ConfigBucketUrl
          - /
          - codepipeline.yaml
      Parameters:
        S3Website: !GetAtt S3Stack.Outputs.S3Website
        S3Build: !GetAtt S3Stack.Outputs.S3Build
        ApiEndpoint: !Join
          - ''
          - - "http://"
            - !GetAtt EC2Stack.Outputs.PublicDNS
            - ":8080"
        CodePipelineRoleArn: !GetAtt IAMStack.Outputs.CodePipelineRoleArn
        FrontendRepositoryId: !Ref FrontendRepository
        BackendRepositoryId: !Ref BackendRepository
        CodeBuildId: !GetAtt CodeBuildStack.Outputs.CodeBuildId

        CodeDeployApplication: !GetAtt CodeDeployStack.Outputs.CodeDeployApplication
        CodeDeployGroupName: !GetAtt CodeDeployStack.Outputs.CodeDeployGroupName

          # Outputs:
          #   NatGateway1EIP:
          #     Description: NATGateway 1
          #     Value: !GetAtt VPCStack.Outputs.NatGateway1EIP
          #   NatGateway2EIP:
          #     Description: NATGateway 2
          #     Value: !GetAtt VPCStack.Outputs.NatGateway2EIP
Outputs:
  S3WebsiteDomain:
    Description: S3Website Domain
    Value: !GetAtt S3Stack.Outputs.S3WebsiteDomain

  CodePipeline:
    Description: CodePipeline
    Value: !GetAtt CodePipelineStack.Outputs.CodePipeline

  CodestarGithubConnection:
    Description: CodestarGithubConnection
    Value: !GetAtt CodePipelineStack.Outputs.CodestarGithubConnection
