AWSTemplateFormatVersion: 2010-09-09
Description: AWS CloudFormation Template for TikTak Project

Resources:
  DynamoDBStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: dynamodb.yaml
  IamStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: iam.yaml
  EC2Stack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ec2.yaml
