AWSTemplateFormatVersion: 2010-09-09
Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: PublicRead
      PublicAccessBlockConfiguration:
         BlockPublicAcls: true
         BlockPublicPolicy: true
         IgnorePublicAcls: true
         RestrictPublicBuckets: true
      BucketName: tiktak-config
      VersioningConfiguration:
        Status: Enabled
    DeletionPolicy: Retain

      # CloudformationDeployPolicy:
      #   Type: AWS::IAM::Policy
      #   Properties:
      #     PolicyName: CloudformationDeployPolicy
      #     PolicyDocument:
      #       Version: 2012-10-17
      #       Statement:
      #       -
      #         Effect: Allow
      #         Action: "dynamodb:*",
      #         Resource: "*"
      #       -
      #         Effect: Allow
      #         Action: "cloudformation:*",
      #         Resource: "*"
      #     Users:
      #       - !Ref TikTakDynamoApiUser

      # CloudformationConfigS3User:
      #   Type: AWS::IAM::User
      #   Properties:
      #     Tags:
      #       -
      #         Key: Name
      #         Value: CloudformationS3User

      # CloudformationConfigPolicy:
      #   Type: AWS::S3::BucketPolicy
      #   Properties:
      #     Bucket: !Ref CloudformationConfigS3Bucket
      #     PolicyDocument:
      #       Statement:
      #         - Action:
      #             - "s3:DeleteObject"
      #             - "s3:GetBucketLocation"
      #             - "s3:GetBucketTagging"
      #             - "s3:GetBucketVersioning"
      #             - "s3:GetObject"
      #             - "s3:GetObjectTagging"
      #             - "s3:GetObjectVersion"
      #             - "s3:GetObjectVersionTagging"
      #             - "s3:ListBucket"
      #             - "s3:PutObject"
      #             - "s3:PutObjectTagging"
      #           Effect: Allow
      #           Resource:
      #             - !Join [ '', [ 'arn:aws:s3:::', !Ref CloudformationConfigS3Bucket ] ]
      #             - !Join [ '', [ 'arn:aws:s3:::', !Ref CloudformationConfigS3Bucket, '/*' ] ]
      #           Principal:
      #             AWS:
      #               - !GetAtt CloudformationConfigS3User.Arn

      # CloudformationConfigKeys:
      #   Type: AWS::IAM::AccessKey
      #   Properties:
      #     UserName: !Ref CloudformationConfigS3User

Outputs:
  S3BucketDomain:
    Description: S3 Bucket Domain name
    Value: !GetAtt S3Bucket.DomainName

      # S3AccessKey:
      #   Description: Access Key for S3 Cloudformation config bucket
      #   Value: !Ref CloudformationConfigKeys

      # S3SecretAccessKey:
      #   Description: Secret Key for S3 Cloudformation config bucket
      #   Value: !GetAtt CloudformationConfigKeys.SecretAccessKey
