AWSTemplateFormatVersion: 2010-09-09
Resources:
  CloudformationConfigS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: PublicRead
      PublicAccessBlockConfiguration:
         BlockPublicAcls: true
         BlockPublicPolicy: true
         IgnorePublicAcls: true
         RestrictPublicBuckets: true
      BucketName: tiktak-cloudformation
      VersioningConfiguration:
        Status: Enabled
    DeletionPolicy: Retain

  CloudformationConfigS3User:
    Type: AWS::IAM::User
    Properties:
      Tags:
        -
          Key: Name
          Value: CloudformationS3User

  CloudformationConfigPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref CloudformationConfigS3Bucket
      PolicyDocument:
        Statement:
          - Action:
              - "s3:DeleteObject"
              - "s3:GetBucketLocation"
              - "s3:GetBucketTagging"
              - "s3:GetBucketVersioning"
              - "s3:GetObject"
              - "s3:GetObjectTagging"
              - "s3:GetObjectVersion"
              - "s3:GetObjectVersionTagging"
              - "s3:ListBucket"
              - "s3:PutObject"
              - "s3:PutObjectTagging"
            Effect: Allow
            Resource:
              - !Join [ '', [ 'arn:aws:s3:::', !Ref CloudformationConfigS3Bucket ] ]
              - !Join [ '', [ 'arn:aws:s3:::', !Ref CloudformationConfigS3Bucket, '/*' ] ]
            Principal:
              AWS:
                - !GetAtt CloudformationConfigS3User.Arn

  CloudformationConfigKeys:
    Type: AWS::IAM::AccessKey
    Properties:
      UserName: !Ref CloudformationConfigS3User

Outputs:
  S3Bucket:
    Description: S3 Bucket for storing cloudformation configs
    Value: !Ref CloudformationConfigS3Bucket

  S3AccessKey:
    Description: Access Key for S3 Cloudformation config bucket
    Value: !Ref CloudformationConfigKeys

  S3SecretAccessKey:
    Description: Secret Key for S3 Cloudformation config bucket
    Value: !GetAtt CloudformationConfigKeys.SecretAccessKey
