package com.cognizant;

import java.util.Date;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName="TikTak")
public class Comment {
	private String gameId;
	private String id;
	private String username;
	private String content;
	private Date createdTime;
	private Date updatedTime;

	public Comment(String gameId, String id, String username, String content, Date createdTime, Date updatedTime) {
		super();
		this.gameId = gameId;
		this.id = id;
		this.username = username;
		this.content = content;
		this.createdTime = createdTime;
		this.updatedTime = updatedTime;
	}
	public Comment() {}

	@DynamoDBHashKey(attributeName = "PK")
	@DynamoDBAutoGeneratedKey()
	public String getGameId() {
		return "GAME#" + gameId;
	}
	public void setGameId(String gameId) {
		this.gameId = gameId;
	}

	@DynamoDBRangeKey(attributeName = "SK")
	@DynamoDBAutoGeneratedKey()
	public String getId() {
		return "COMMENT#" + id;
	}
	public void setId(String id) {
		this.id = id;
	}

	@DynamoDBAttribute(attributeName = "username")
	public String getUsername() {
		return username;
	}
	public void setUsername(String username) {
		this.username = username;
	}

	@DynamoDBAttribute(attributeName = "content")
	public String getContent() {
		return content;
	}
	public void setContent(String content) {
		this.content = content;
	}

	@DynamoDBAttribute(attributeName = "createdTime")
	public Date getCreatedTime() {
		return createdTime;
	}
	public void setCreatedTime(Date createdTime) {
		this.createdTime = createdTime;
	}

	@DynamoDBAttribute(attributeName = "updatedTime")
	public Date getUpdatedTime() {
		return updatedTime;
	}
	public void setUpdatedTime(Date updatedTime) {
		this.updatedTime = updatedTime;
	}
}
