package com.cognizant.TikTak;

import java.util.Date;
import java.util.List;
import java.util.ArrayList;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName="TikTak")
public class Game {
	private String id;

	private String username1;
	private String username2;

	private Date createdTime;
	private Date updatedTime;

	private List<GameMove> gameMoves;

	public Game() {
		this.gameMoves = new ArrayList<>();
	}

	public Game(String id, String username1, String username2, Date createdTime,
			Date updatedTime, List<com.cognizant.TicTac.GameMove> gameMoves) {
		this();
		this.id = id;
		this.username1 = username1;
		this.username2 = username2;
		this.createdTime = createdTime;
		this.updatedTime = updatedTime;
		this.gameMoves = gameMoves;
	}

	@DynamoDBHashKey(attributeName = "PK")
	@DynamoDBAutoGeneratedKey()
	public String getId() {
		return "GAME#" + id;
	}
	public void setId(String id) {
		this.id = id;
	}

	@DynamoDBAttribute(attributeName = "gameMoves")
	public List<GameMove> getGameMoves() {
		return gameMoves;
	}
	public void setGameMoves(List<GameMove> gameMoves) {
		this.gameMoves = gameMoves;
	}

	@DynamoDBAttribute(attributeName = "username1")
	public String getUsername1() {
		return username1;
	}
	public void setUsername1(String username1) {
		this.username1 = username1;
	}

	@DynamoDBAttribute(attributeName = "username2")
	public String getUsername2() {
		return username2;
	}
	public void setUsername2(String username2) {
		this.username2 = username2;
	}

	@DynamoDBAttribute(attributeName = "createdTime")
	public Date getCreatedTime() {
		return createdTime;
	}
	public void setCreatedTime(Date createdTime) {
		this.createdTime = createdTime;
	}

	@DynamoDBAttribute(attributeName = "updatedTime")
	public Date getUpdatedTime() {
		return updatedTime;
	}
	public void setUpdatedTime(Date updatedTime) {
		this.updatedTime = updatedTime;
	}
}
